package com.vlv.imperiya.core.ui.theme

import androidx.compose.ui.graphics.Color


// Text Colors
val Title_Color = Color(0xFFFFFFFF)
val Sub_Title_Color = Color(0xFFFFFFFF)
val Sub_Title2_Color = Color(0xCCFFFFFF)
val Paragraph_Color = Color(0xFFFFFFFF)
val Hint_Color = Color(0x8f0FFFFFF)
val Link = Color(0xFF46BFFE)

// Others
val color_imperiya_light_primary = Color(0xFF006686)
val color_imperiya_light_onPrimary = Color(0xFFFFFFFF)
val color_imperiya_light_primaryContainer = Color(0xFFC0E8FF)
val color_imperiya_light_onPrimaryContainer = Color(0xFF001E2B)
val color_imperiya_light_secondary = Color(0xFF1D6FBF)
val color_imperiya_light_onSecondary = Color(0xFFFFFFFF)
val color_imperiya_light_secondaryContainer = Color(0xFFD3E3FF)
val color_imperiya_light_onSecondaryContainer = Color(0xFF001C39)
val color_imperiya_light_tertiary = Color(0xFF006684)
val color_imperiya_light_onTertiary = Color(0xFFFFFFFF)
val color_imperiya_light_tertiaryContainer = Color(0xFFBDE9FF)
val color_imperiya_light_onTertiaryContainer = Color(0xFF001F2A)
val color_imperiya_light_error = Color(0xFFBA1A1A)
val color_imperiya_light_errorContainer = Color(0xFFFFDAD6)
val color_imperiya_light_onError = Color(0xFFFFFFFF)
val color_imperiya_light_onErrorContainer = Color(0xFF410002)
val color_imperiya_light_background = Color(0xFFFBFCFE)
val color_imperiya_light_onBackground = Color(0xFF191C1E)
val color_imperiya_light_surface = Color(0xFFFBFCFE)
val color_imperiya_light_onSurface = Color(0xFF191C1E)
val color_imperiya_light_surfaceVariant = Color(0xFFDCE3E9)
val color_imperiya_light_onSurfaceVariant = Color(0xFF40484C)
val color_imperiya_light_outline = Color(0xFF71787D)
val color_imperiya_light_inverseOnSurface = Color(0xFFF0F1F3)
val color_imperiya_light_inverseSurface = Color(0xFF2E3133)
val color_imperiya_light_inversePrimary = Color(0xFF71D2FF)
val color_imperiya_light_shadow = Color(0xFF000000)
val color_imperiya_light_surfaceTint = Color(0xFF006686)
val color_imperiya_light_outlineVariant = Color(0xFFC0C7CD)
val color_imperiya_light_scrim = Color(0xFF000000)

val color_imperiya_dark_primary = Color(0xFF71D2FF)
val color_imperiya_dark_onPrimary = Color(0xFF003547)
val color_imperiya_dark_primaryContainer = Color(0xFF004D66)
val color_imperiya_dark_onPrimaryContainer = Color(0xFFC0E8FF)
val color_imperiya_dark_secondary = Color(0xFF96C2FF)
val color_imperiya_dark_onSecondary = Color(0xFF00315D)
val color_imperiya_dark_secondaryContainer = Color(0xFF004883)
val color_imperiya_dark_onSecondaryContainer = Color(0xFFD3E3FF)
val color_imperiya_dark_tertiary = Color(0xFF67D3FF)
val color_imperiya_dark_onTertiary = Color(0xFF003546)
val color_imperiya_dark_tertiaryContainer = Color(0xFF004D64)
val color_imperiya_dark_onTertiaryContainer = Color(0xFFBDE9FF)
val color_imperiya_dark_error = Color(0xFFFF6B6B)
val color_imperiya_dark_errorContainer = Color(0xFF93000A)
val color_imperiya_dark_onError = Color(0xFF690005)
val color_imperiya_dark_onErrorContainer = Color(0xFFFFDAD6)
val color_imperiya_dark_background = Color(0xFF191C1E)
val color_imperiya_dark_onBackground = Color(0xFFE1E2E5)
val color_imperiya_dark_surface = Color(0xFF191C1E)
val color_imperiya_dark_onSurface = Color(0xFFE1E2E5)
val color_imperiya_dark_surfaceVariant = Color(0xFF40484C)
val color_imperiya_dark_onSurfaceVariant = Color(0xFFC0C7CD)
val color_imperiya_dark_outline = Color(0xFF8A9297)
val color_imperiya_dark_inverseOnSurface = Color(0xFF191C1E)
val color_imperiya_dark_inverseSurface = Color(0xFFE1E2E5)
val color_imperiya_dark_inversePrimary = Color(0xFF006686)
val color_imperiya_dark_shadow = Color(0xFF000000)
val color_imperiya_dark_surfaceTint = Color(0xFF71D2FF)
val color_imperiya_dark_outlineVariant = Color(0xFF40484C)
val color_imperiya_dark_scrim = Color(0xFF000000)