name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build-views:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Config Env.properties
        run: echo 'api_key=${{ secrets.API_KEY }}' > env.properties
      - name: Build with Gradle
        run: ./gradlew :app:assembleViewsDebug

  views-instrumentation-tests:
    needs: [build-views]
    runs-on: macos-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Config Env.properties
        run: echo 'api_key=${{ secrets.API_KEY }}' > env.properties

      - name: Run espresso tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          arch: x86_64
          disable-animations: true
          profile: Nexus 6
          script: ./gradlew createViewsDebugCoverageReport
